name: Feature Request
description: Suggest a new feature for this plugin.
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a feature request! To ensure this isn’t already on our radar, please first search [existing issues](https://github.com/putyourlightson/craft-blitz/issues?q=is%3Aissue).

        If you still believe you have a new suggestion, please provide a clear and concise description, including:
        - What problem you believe your feature request can solve.
        - Any alternative solutions or features you have already considered.
  - type: textarea
    id: body
    attributes:
      label: Feature Request
      description: Please provide a clear and concise suggestion for a feature.
    validations:
      required: true
  - type: input
    id: pluginVersion
    attributes:
      label: Plugin Version
      description: Provide the plugin version that this relates to, ideally the [latest version](https://github.com/putyourlightson/craft-blitz/blob/develop/CHANGELOG.md).
      placeholder: 4.10.0
